// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DylexiaSettings
{
    internal sealed partial class Vsix
    {
        public const string Id = "DylexiaSettings.70833502-b6c7-40a9-8e8f-91c0aeed7f62";
        public const string Name = "DylexiaSettings";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Sandy Grawe";
        public const string Tags = "";
    }
}
